// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_mTALZQ5bZLiRR3QBPAkD4kY25EuKfOo',
    appId: '1:777500637733:web:cb12ab923e240238e59dcc',
    messagingSenderId: '777500637733',
    projectId: 'school-repo-23fe6',
    authDomain: 'school-repo-23fe6.firebaseapp.com',
    storageBucket: 'school-repo-23fe6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PjV38s7CTd1uIQI786dDPrQ4UA7kam8',
    appId: '1:777500637733:android:1502b40869c24736e59dcc',
    messagingSenderId: '777500637733',
    projectId: 'school-repo-23fe6',
    storageBucket: 'school-repo-23fe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDaCePDBNUpUojniOENLhoqPc9uBYSIrw',
    appId: '1:777500637733:ios:e9289de753d866aae59dcc',
    messagingSenderId: '777500637733',
    projectId: 'school-repo-23fe6',
    storageBucket: 'school-repo-23fe6.firebasestorage.app',
    iosBundleId: 'com.example.shoolRepo',
  );
}
